My EDA will be how unhealthy lifestyles such as above or below bmi and smoking effects the charges of patients

In [15]:
import os
import sys
module_path = os.path.abspath(os.path.join('.'))
if module_path not in sys.path:
    sys.path.append(module_path)
import project_functions
url='https://raw.githubusercontent.com/data301-2020-winter2/course-project-group_1017/main/Data/Raw/medical_expenses.csv'

In [16]:
project_functions.load_and_process(url)

      age     sex   bmi  Dependents smoker region   charges
0      18    male  23.2           0     no     SE   1121.87
1      18    male  30.1           0     no     SE   1131.51
2      18    male  33.3           0     no     SE   1135.94
3      18    male  33.7           0     no     SE   1136.40
4      18    male  34.1           0     no     SE   1137.01
...   ...     ...   ...         ...    ...    ...       ...
1333   33  female  35.5           0    yes     NW  55135.40
1334   31  female  38.1           1    yes     NE  58571.07
1335   52    male  34.5           3    yes     NW  60021.40
1336   45    male  30.4           0    yes     SE  62592.87
1337   54  female  47.4           0    yes     SE  63770.43

[1338 rows x 7 columns]

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("ticks")
sns.set_theme("paper")

In [23]:
project_functions.Healthy(url)

AttributeError: module 'project_functions' has no attribute 'Healthy'